name: hpspells
main: com.blogspot.coocoo617.Main
version: 1.0
commands:
  aguamenti:
    description: Produces a splash of water from the caster's wand.
    usage: /aguamenti
    permission: hpspells.aguamenti
  avis:
    description: Creates a flock of birds from the caster's wand.
    usage: /avis
    permission: hpspells.avis
  confringo:
    description: Causes anything that the spell meets to explode in flames.
    usage: /confringo
    permission: hpspells.confringo
  confundo:
    description: Causes the victim to become confused.
    usage: /confundo <player>
    permission: hpspells.confundo
  conjunctivitus:
    description: A curse that causes great pain to the victim's eyes.
    usage: /conjunctivitus <player>
    permission: hpspells.conjunctivitus
  freezing:
    description: Renders target immobile.
    usage: /freezing <player>
    permission: hpspells.freezing
permissions:
  hpspells.*:
    description: Gives access to all doorman commands
    children:
      hpspells.aguamenti: true
      hpspells.avis: true
      hpspells.confringo: true
      hpspells.confundo: true
      hpspells.conjunctivitus: true
      hpspells.freezing: true
  hpspells.aguamenti:
    description: Produces a splash of water from the caster's wand.
    default: op
  hpspells.avis:
    description: Creates a flock of birds from the caster's wand.
    default: op
  hpspells.confringo:
    description: Causes anything that the spell meets to explode in flames.
    default: op
  hpspells.confundo:
    description: Causes the victim to become confused.
    default: op
  hpspells.conjunctivitus:
    description: A curse that causes great pain to the victim's eyes..
    default: op
  hpspells.freezing:
    description: Renders target immobile.
    default: op